name: entrance_test
description: A new Flutter project.
publish_to: 'none'
version: 18.1.20+31

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  ansicolor: ^2.0.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  country_code_picker: ^3.0.0
  dio: ^5.4.3+1
  dots_indicator: ^3.0.0
  downloads_path_provider_28: ^0.1.2
  dynamic_height_grid_view: ^0.0.4
  flutter:
    sdk: flutter

  flutter_downloader: ^1.11.7
  flutter_inappwebview: ^6.0.0
  flutter_web_browser: ^0.17.1
  get: ^4.6.6
  get_storage: ^2.1.1
  http: ^1.2.1
  intl: ^0.19.0
  path_provider: ^2.1.3
  permission_handler: ^11.3.1
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1
  talker_dio_logger: ^4.2.0
  url_launcher: ^6.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
